### test
POST http://localhost:8080/miss/fruit/detail?name=watermelon



### test add
POST http://localhost:8088/miss/fruit/add
Accept: application/json;*/*;charset=UTF-8
Content-Type: application/json

{
  "nam e": "epeach",
  "age": 19
}
